# Generated by Django 6.0.2 on 2026-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer'), ('guest', 'Guest')], default='guest', max_length=20, null=True, verbose_name='role'),
        ),
    ]
