# Generated by Django 6.0.2 on 2026-05-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
